package com.cos.photogramstart.handler.aop;

import java.util.HashMap;
import java.util.Map;

import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.springframework.stereotype.Component;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;

import com.cos.photogramstart.handler.ex.CustomValidationApiException;
import com.cos.photogramstart.handler.ex.CustomValidationException;

@Component //RestContorller, Service 모든 것들이 Component를 상속해서 만들어져 있음.
@Aspect
public class ValidationAdivice {

	// execution()안에 처음은 접근제한자가 들어오게된다.(public,private,등)
	// *로하면 모든 접근제한자 허용
	@Around("execution(* com.cos.photogramstart.web.api.*Controller.*(..))") // 시작과 끝까지 간섭
	// web.*Controller = webn의 모든Controller로 끝나는것
	// *Controller.*(..) = 컨트롤러의 모든 메서드 (..)은 모든 파라미터의 값이 어떤것이든 하겠다는뜻.
	public Object apiAdivice(ProceedingJoinPoint proceedingJoinPoint) throws Throwable{
		System.out.println("web api 컨트롤러");
		Object[] args = proceedingJoinPoint.getArgs();
		for(Object arg : args) {
			if(arg instanceof BindingResult) {
				System.out.println("유효성 검사를 하는 함수입니다.");
				BindingResult bindingResult = (BindingResult) arg;
				if(bindingResult.hasErrors()) {
					Map<String, String>errorMap = new HashMap<>();
					for(FieldError error : bindingResult.getFieldErrors()) {
						errorMap.put(error.getField(), error.getDefaultMessage());
					}
					throw new CustomValidationApiException("유효성검사 실패함",errorMap);
				}
			}
		}
		return proceedingJoinPoint.proceed();
	}
	
	@Around("execution(* com.cos.photogramstart.web.*Controller.*(..))") // 시작과 끝까지 간섭
	public Object advice(ProceedingJoinPoint proceedingJoinPoint) throws Throwable{
		System.out.println("web 컨트롤러");
		Object[] args = proceedingJoinPoint.getArgs();
		for(Object arg : args) {
			if(arg instanceof BindingResult) {
				BindingResult bindingResult = (BindingResult) arg;
				if(bindingResult.hasErrors()) {
					Map<String, String>errorMap = new HashMap<>();
					
												// 모든 에러가 getFieldErrors에 리스트 형태로 담겨있다.
					for(FieldError error : bindingResult.getFieldErrors()) {
						errorMap.put(error.getField(), error.getDefaultMessage());
					}
					// exception을 발동시켜 에러를 던진다
					throw new CustomValidationException("유효성검사 실패함",errorMap);
				}
			}
		}
		return proceedingJoinPoint.proceed(); // 이때 해당함수가 실행된다.
	}
	// proceedingJoinPoint 해당 메서드에 모든 정보가 있다
	// 실행은 해당 메서드보다 먼저 Advice함수가 실행된다.
	
}
